# Generated by Django 5.0.7 on 2024-07-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_create_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(null=True, verbose_name='Url to photo'),
        ),
    ]
